version: "2"
linters:
  enable:
    - misspell
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/chrismdemian/laurus
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
